TWITTER_ACCOUNT:
  CONSUMER_KEY: 6Nz3s8WXdcAMErllE0WHD9uHQ
  CONSUMER_SECRET: bIubQvXhD1h7jlhbHaJhOw51VLya8F8caTQsE1NatnUHUl5spy
  ACCESS_TOKEN: 1252730898933583874-owSxqAutpVKufY8amQyizogHIFnBrk
  ACCESS_TOKEN_SECRET: FpfaOpjCJFgjRSvDhLY30BgLpqj5SuxvbderMQ6EjMEHp